SET DEFINE OFF

-- DASHBOARD 1: Summary by service and status
SELECT
    R.SERVICE_NAME,
    R.OPERATION_TYPE,
    COUNT(L.LOG_ID)                                              AS TOTAL,
    SUM(CASE WHEN L.FINAL_STATUS='SENT'             THEN 1 END) AS LEG1_PENDING,
    SUM(CASE WHEN L.FINAL_STATUS='SUCCESS'          THEN 1 END) AS LEG2_SUCCESS,
    SUM(CASE WHEN L.FINAL_STATUS='FAILED'           THEN 1 END) AS LEG1_FAILED,
    SUM(CASE WHEN L.FINAL_STATUS='VALIDATION_FAILED'THEN 1 END) AS VALIDATION_FAIL,
    SUM(CASE WHEN L.FINAL_STATUS='RECORD_NOT_FOUND' THEN 1 END) AS NOT_FOUND,
    SUM(CASE WHEN L.FINAL_STATUS='DUPLICATE_RECORD' THEN 1 END) AS DUPLICATE,
    SUM(CASE WHEN L.FINAL_STATUS='TIMEOUT'          THEN 1 END) AS TIMEOUT,
    SUM(CASE WHEN L.FINAL_STATUS='EXHAUSTED'        THEN 1 END) AS EXHAUSTED,
    ROUND(
        SUM(CASE WHEN L.FINAL_STATUS='SUCCESS' THEN 1 ELSE 0 END) * 100.0 /
        NULLIF(COUNT(L.LOG_ID),0), 1)                            AS SUCCESS_PCT
FROM CRM_MPM_API_REGISTRY R
LEFT JOIN CRM_MPM_CRM_INTEGRATION_LOG L
       ON L.REGISTRY_ID = R.REGISTRY_ID
WHERE R.IS_ACTIVE = 'Y'
GROUP BY R.SERVICE_NAME, R.OPERATION_TYPE
ORDER BY R.SERVICE_NAME;


-- DASHBOARD 2: Full detail — every record with LEG1 + LEG2 reference numbers
SELECT
    R.SERVICE_NAME,
    L.LOG_ID,
    L.SOURCE_RECORD_ID                                        AS ORACLE_KEY,
    L.ATTEMPT_NO,
    L.FINAL_STATUS,
    -- LEG 1 reference
    L.HTTP_STATUS_CODE                                        AS HTTP,
    L.ACK_STATUS_CODE                                         AS ACK_STATUS,
    L.ACK_REQUEST_ID                                          AS APIC_REQUEST_ID,
    L.ACK_RESPONSE_TIMESTAMP                                  AS CRM_RECEIVED_AT,
    L.X_UNIQUE_ID                                             AS OUTBOUND_TRACE_ID,
    -- LEG 2 reference
    L.CRM_ENTITY_ID                                           AS D365_ENTITY_ID,
    L.CALLBACK_RESULT_CODE,
    SUBSTR(L.CALLBACK_RESULT_DESC,1,50)                       AS CALLBACK_DESC,
    L.CALLBACK_X_UNIQUE_ID                                    AS CALLBACK_TRACE_ID,
    L.CALLBACK_CHANNEL_ID,
    -- Timing
    TO_CHAR(L.SENT_DATE,    'DD-MON-YYYY HH24:MI:SS')         AS LEG1_SENT,
    TO_CHAR(L.CALLBACK_DATE,'DD-MON-YYYY HH24:MI:SS')         AS LEG2_RECEIVED,
    CASE
        WHEN L.CALLBACK_DATE IS NOT NULL AND L.SENT_DATE IS NOT NULL
        THEN ROUND((L.CALLBACK_DATE - L.SENT_DATE)*86400,1)||'s'
        WHEN L.FINAL_STATUS = 'SENT'
        THEN ROUND((SYSTIMESTAMP - L.SENT_DATE)*1440,1)||' mins waiting'
        ELSE NULL
    END                                                        AS RESPONSE_TIME,
    -- Error
    SUBSTR(L.ERROR_MESSAGE,1,100)                              AS ERROR_MSG
FROM CRM_MPM_CRM_INTEGRATION_LOG L
JOIN CRM_MPM_API_REGISTRY         R ON R.REGISTRY_ID = L.REGISTRY_ID
ORDER BY L.LOG_ID DESC
FETCH FIRST 100 ROWS ONLY;


-- DASHBOARD 3: Callback audit — what ESB received and what Oracle returned
SELECT
    A.AUDIT_ID,
    TO_CHAR(A.RECEIVED_AT,'DD-MON-YYYY HH24:MI:SS') AS CALLBACK_AT,
    A.SERVICE_NAME,
    A.X_UNIQUE_ID                                    AS CALLBACK_TRACE_ID,
    A.CHANNEL_ID,
    A.REQUEST_ID                                     AS CRM_REQUEST_ID,
    A.STATUS_CODE                                    AS CRM_STATUS,
    A.RESULT_CODE                                    AS CRM_RESULT,
    A.PROCESSING_STATUS                              AS ORACLE_STATUS,
    A.MATCHED_LOG_ID,
    A.STATUS_CODE_SENT                               AS ORACLE_CODE_TO_ESB,
    SUBSTR(A.DESCRIPTION_SENT,1,80)                  AS ORACLE_DESC_TO_ESB,
    SUBSTR(A.RESPONSE_SENT,1,100)                    AS JSON_TO_ESB
FROM CRM_MPM_CALLBACK_AUDIT_LOG A
ORDER BY A.AUDIT_ID DESC
FETCH FIRST 50 ROWS ONLY;


-- DASHBOARD 4: Pending action items
SELECT 'WAITING LEG2 CALLBACK'       AS STATUS,
       R.SERVICE_NAME,
       L.LOG_ID, L.SOURCE_RECORD_ID,
       L.ACK_REQUEST_ID,
       ROUND((SYSTIMESTAMP-L.SENT_DATE)*1440,1) AS MINS_WAITING
FROM CRM_MPM_CRM_INTEGRATION_LOG L
JOIN CRM_MPM_API_REGISTRY R ON R.REGISTRY_ID = L.REGISTRY_ID
WHERE L.FINAL_STATUS = 'SENT'
UNION ALL
SELECT 'RETRY ELIGIBLE',
       R.SERVICE_NAME,
       L.LOG_ID, L.SOURCE_RECORD_ID,
       L.ACK_REQUEST_ID,
       ROUND((SYSTIMESTAMP-L.SENT_DATE)*1440,1)
FROM CRM_MPM_CRM_INTEGRATION_LOG L
JOIN CRM_MPM_API_REGISTRY R ON R.REGISTRY_ID = L.REGISTRY_ID
WHERE L.FINAL_STATUS IN ('FAILED','TIMEOUT')
  AND L.RETRY_COUNT < R.MAX_RETRY_COUNT
  AND L.IS_FINAL_ATTEMPT = 'N'
UNION ALL
SELECT 'NEEDS MANUAL INTERVENTION',
       R.SERVICE_NAME,
       L.LOG_ID, L.SOURCE_RECORD_ID,
       L.ACK_REQUEST_ID,
       ROUND((SYSTIMESTAMP-L.SENT_DATE)*1440,1)
FROM CRM_MPM_CRM_INTEGRATION_LOG L
JOIN CRM_MPM_API_REGISTRY R ON R.REGISTRY_ID = L.REGISTRY_ID
WHERE L.FINAL_STATUS = 'EXHAUSTED'
ORDER BY 1, 2;


-- DASHBOARD 5: Scheduler health
SELECT JOB_NAME, STATUS,
       TO_CHAR(START_TIME,'DD-MON-YYYY HH24:MI:SS') AS STARTED,
       TO_CHAR(END_TIME,  'DD-MON-YYYY HH24:MI:SS') AS ENDED,
       RECORDS_PROCESSED, RECORDS_SUCCESS, RECORDS_FAILED,
       SUBSTR(ERROR_MESSAGE,1,100) AS ERROR_MSG
FROM CRM_MPM_JOB_RUN_HISTORY
ORDER BY RUN_ID DESC
FETCH FIRST 20 ROWS ONLY;


-- DASHBOARD 6: Watermark — next pickup per service
SELECT R.SERVICE_NAME, R.SOURCE_VIEW,
       TO_CHAR(W.LAST_PROCESSED_TS,'DD-MON-YYYY HH24:MI:SS') AS NEXT_PICKUP_FROM,
       W.LAST_RUN_STATUS, W.LAST_RUN_RECORDS
FROM CRM_MPM_API_WATERMARK W
JOIN CRM_MPM_API_REGISTRY  R ON R.REGISTRY_ID = W.REGISTRY_ID
ORDER BY R.SERVICE_NAME;
```