-- QUERY 1: Scheduler job status
SELECT JOB_NAME, ENABLED, STATE, LAST_START_DATE,
       NEXT_RUN_DATE, FAILURE_COUNT
FROM   DBA_SCHEDULER_JOBS
WHERE  JOB_NAME LIKE 'CRM_MPM%'
ORDER  BY JOB_NAME;

-- QUERY 2: Job run history
SELECT JOB_NAME, STATUS, START_TIME, END_TIME,
       RECORDS_PROCESSED, RECORDS_SUCCESS, RECORDS_FAILED, ERROR_MESSAGE
FROM   CRM_MPM_JOB_RUN_HISTORY
WHERE  JOB_NAME IN ('UNIT_STATUS_BATCH','OUTBOUND_PUSH','RETRY_JOB')
ORDER  BY START_TIME DESC FETCH FIRST 20 ROWS ONLY;

-- QUERY 3: Unit records in integration log
SELECT ENTITY_NAME, OPERATION_TYPE, FINAL_STATUS,
       COUNT(*) AS REC_COUNT, MAX(SENT_DATE) AS LAST_SENT
FROM   CRM_MPM_CRM_INTEGRATION_LOG
WHERE  ENTITY_NAME LIKE '%UNIT%'
GROUP  BY ENTITY_NAME, OPERATION_TYPE, FINAL_STATUS
ORDER  BY LAST_SENT DESC;

-- QUERY 4: Enable jobs (uncomment when ready)
/*
BEGIN
    DBMS_SCHEDULER.ENABLE('CRM_MPM_UNIT_STATUS_JOB');
    DBMS_SCHEDULER.ENABLE('CRM_MPM_UNIT_UNAVAILABLE_JOB');
END;
/
*/
