SET DEFINE OFF

ALTER TABLE CRM_MPM_CALLBACK_AUDIT_LOG ADD (
    STATUS_CODE_SENT  VARCHAR2(20),
    DESCRIPTION_SENT  VARCHAR2(500)
);

COMMENT ON COLUMN CRM_MPM_CALLBACK_AUDIT_LOG.STATUS_CODE_SENT IS
  'p_status_code returned to ESB: CB_0000/CB_1001/CB_1002/CB_1003';
COMMENT ON COLUMN CRM_MPM_CALLBACK_AUDIT_LOG.DESCRIPTION_SENT IS
  'p_description returned to ESB: human readable result';

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'CRM_MPM_CALLBACK_AUDIT_LOG'
ORDER BY COLUMN_ID;

PROMPT ============================================================
PROMPT  STATUS_CODE_SENT and DESCRIPTION_SENT columns added.
PROMPT  Recompile PKG_CRM_INTEGRATION_BODY_FINAL.sql after this.
PROMPT ============================================================
