SET DEFINE OFF

ALTER TABLE CRM_MPM_CRM_INTEGRATION_LOG ADD (
    CALLBACK_X_UNIQUE_ID  VARCHAR2(60),
    CALLBACK_CHANNEL_ID   VARCHAR2(20)
);

COMMENT ON COLUMN CRM_MPM_CRM_INTEGRATION_LOG.CALLBACK_X_UNIQUE_ID IS
  'x-unique-id header from ESB LEG 2 callback — cross-reference with outbound X_UNIQUE_ID';
COMMENT ON COLUMN CRM_MPM_CRM_INTEGRATION_LOG.CALLBACK_CHANNEL_ID IS
  'x-channel-id header from ESB LEG 2 callback — e.g. PCRM';

SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'CRM_MPM_CRM_INTEGRATION_LOG'
  AND COLUMN_NAME IN ('CALLBACK_X_UNIQUE_ID','CALLBACK_CHANNEL_ID');

PROMPT ============================================================
PROMPT  Run order:
PROMPT    1. This script  (ALTER TABLE)
PROMPT    2. PKG_CRM_INTEGRATION_SPEC.sql
PROMPT    3. PKG_CRM_INTEGRATION_BODY_FINAL.sql
PROMPT ============================================================
