/* ============================================================================
   XXMPM ESB INTEGRATION — COMPLETE TABLE DESIGN
   Uses your REAL existing views (confirmed from SQL Developer screenshot):

   XXMPM_CRM_PROPERTY_CREATE_V       XXMPM_CRM_PROPERTY_UPDATE_V
   XXMPM_CRM_BUILDING_CREATE_V       XXMPM_CRM_BUILDING_UPDATE_V
   XXMPM_CRM_FLOOR_CREATE_V          XXMPM_CRM_FLOOR_UPDATE_V
   XXMPM_CRM_UNIT_CREATE_V           XXMPM_CRM_UNIT_UPDATE_V
   XXMPM_CRM_UNIT_STATUS_UPDATE_V

   All 9 views confirmed to have:
     UNIQUE_ID         (present, NOT used as watermark)
     LAST_UPDATE_DATE  (present, USED as watermark)
   ============================================================================ */


/* ============================================================================
   TABLE 1: XXMPM_API_CREDENTIALS
   ============================================================================ */
CREATE TABLE XXMPM_API_CREDENTIALS (
    CRED_CODE         VARCHAR2(50)   NOT NULL,
    TOKEN_URL         VARCHAR2(500)  NOT NULL,
    CLIENT_ID         VARCHAR2(200)  NOT NULL,
    CLIENT_SECRET_REF VARCHAR2(500)  NOT NULL,
    GRANT_TYPE        VARCHAR2(50)   DEFAULT 'client_credentials',
    SCOPE             VARCHAR2(200),
    TOKEN_CACHE_VALUE VARCHAR2(4000),
    TOKEN_EXPIRY      TIMESTAMP,
    IS_ACTIVE         VARCHAR2(1)    DEFAULT 'Y',
    CREATED_DATE      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_DATE      TIMESTAMP,
    CONSTRAINT PK_XXMPM_CREDENTIALS PRIMARY KEY (CRED_CODE)
);

INSERT INTO XXMPM_API_CREDENTIALS (
    CRED_CODE, TOKEN_URL, CLIENT_ID, CLIENT_SECRET_REF, GRANT_TYPE, SCOPE, IS_ACTIVE
) VALUES (
    'MPM_APIC_CRED',
    'https://apisitgatewaylb.adib.co.ae:443/adib/oauth-client/oauth2/token',
    'bdbd7c57145bcbaaf4e81bdc16181287',
    'cb9ed345fcc99e9c165049a6f608ee5b',
    'client_credentials',
    'powerapp:access',
    'Y'
);
COMMIT;


/* ============================================================================
   TABLE 2: XXMPM_API_REGISTRY — master config, one row per real view
   ============================================================================ */
CREATE TABLE XXMPM_API_REGISTRY (
    REGISTRY_ID            NUMBER         NOT NULL,
    ENTITY_NAME            VARCHAR2(100)  NOT NULL,
    SERVICE_NAME           VARCHAR2(100)  NOT NULL,
    OPERATION_TYPE         VARCHAR2(20)   NOT NULL,
    CRED_CODE              VARCHAR2(50)   NOT NULL,
    APIC_ENDPOINT_URL      VARCHAR2(500)  NOT NULL,
    APIC_API_VERSION       VARCHAR2(20)   DEFAULT '1',
    HTTP_METHOD             VARCHAR2(10)   DEFAULT 'POST',
    RECORD_TYPE_HDR        VARCHAR2(100)  NOT NULL,
    EVENT_CODE_HDR         VARCHAR2(50)   NOT NULL,
    SOURCE_VIEW            VARCHAR2(128)  NOT NULL,
    SOURCE_KEY_COL         VARCHAR2(128)  NOT NULL,
    SOURCE_FILTER_COL      VARCHAR2(128)  DEFAULT 'LAST_UPDATE_DATE',
    SOURCE_TYPE            VARCHAR2(20)   DEFAULT 'VIEW',
    SOURCE_PROC            VARCHAR2(128),
    JSON_MAPPING_NAME      VARCHAR2(100)  NOT NULL,
    MAX_RETRY_COUNT        NUMBER         DEFAULT 3,
    TIMEOUT_MINUTES        NUMBER         DEFAULT 30,
    RETRY_INTERVAL_MINUTES NUMBER         DEFAULT 10,
    CALLBACK_TARGET_TABLE  VARCHAR2(128),
    CALLBACK_STATUS_COL    VARCHAR2(128),
    CALLBACK_REF_COL       VARCHAR2(128),
    CALLBACK_KEY_COL       VARCHAR2(128),
    POST_CALLBACK_PROC     VARCHAR2(128),
    IS_ACTIVE              VARCHAR2(1)    DEFAULT 'Y',
    CREATED_DATE           TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_DATE           TIMESTAMP,
    CONSTRAINT PK_XXMPM_REGISTRY PRIMARY KEY (REGISTRY_ID),
    CONSTRAINT UQ_XXMPM_REGISTRY_SVC UNIQUE (SERVICE_NAME),
    CONSTRAINT FK_XXMPM_REG_CRED FOREIGN KEY (CRED_CODE)
        REFERENCES XXMPM_API_CREDENTIALS(CRED_CODE)
);

-- ── 9 REAL registries, matching your actual view names exactly ─────────────

-- PROPERTY CREATE
INSERT INTO XXMPM_API_REGISTRY (
    REGISTRY_ID, ENTITY_NAME, SERVICE_NAME, OPERATION_TYPE, CRED_CODE,
    APIC_ENDPOINT_URL, APIC_API_VERSION, HTTP_METHOD, RECORD_TYPE_HDR, EVENT_CODE_HDR,
    SOURCE_VIEW, SOURCE_KEY_COL, SOURCE_FILTER_COL, JSON_MAPPING_NAME,
    MAX_RETRY_COUNT, TIMEOUT_MINUTES, RETRY_INTERVAL_MINUTES,
    CALLBACK_TARGET_TABLE, CALLBACK_STATUS_COL, CALLBACK_REF_COL, CALLBACK_KEY_COL, IS_ACTIVE
) VALUES (
    101, 'Property', 'XXMPM_CRM_PROPERTY_CREATE', 'CREATE', 'MPM_APIC_CRED',
    'https://apiditgateway.adib.co.ae/adib/powerautomate/automations/direct/workflows/e287bb6987cc4254bfbaa954d3fd4954/triggers/manual/paths/invoke',
    '1', 'POST', 'md_project', '100000000',
    'XXMPM_CRM_PROPERTY_CREATE_V', 'PROPERTY_ID', 'LAST_UPDATE_DATE', 'XXMPM_PROPERTY_CREATE_MAPPING',
    3, 30, 10,
    'MPM_PROPERTIES', 'CRM_SYNC_STATUS', 'CRM_REFERENCE_NO', 'PROPERTY_ID', 'Y'
);

-- PROPERTY UPDATE
INSERT INTO XXMPM_API_REGISTRY (
    REGISTRY_ID, ENTITY_NAME, SERVICE_NAME, OPERATION_TYPE, CRED_CODE,
    APIC_ENDPOINT_URL, APIC_API_VERSION, HTTP_METHOD, RECORD_TYPE_HDR, EVENT_CODE_HDR,
    SOURCE_VIEW, SOURCE_KEY_COL, SOURCE_FILTER_COL, JSON_MAPPING_NAME,
    MAX_RETRY_COUNT, TIMEOUT_MINUTES, RETRY_INTERVAL_MINUTES,
    CALLBACK_TARGET_TABLE, CALLBACK_STATUS_COL, CALLBACK_REF_COL, CALLBACK_KEY_COL, IS_ACTIVE
) VALUES (
    102, 'Property', 'XXMPM_CRM_PROPERTY_UPDATE', 'UPDATE', 'MPM_APIC_CRED',
    'https://apiditgateway.adib.co.ae/adib/powerautomate/automations/direct/workflows/e287bb6987cc4254bfbaa954d3fd4954/triggers/manual/paths/invoke',
    '1', 'POST', 'md_project', '100000001',
    'XXMPM_CRM_PROPERTY_UPDATE_V', 'PROPERTY_ID', 'LAST_UPDATE_DATE', 'XXMPM_PROPERTY_UPDATE_MAPPING',
    3, 30, 10,
    'MPM_PROPERTIES', 'CRM_SYNC_STATUS', 'CRM_REFERENCE_NO', 'PROPERTY_ID', 'Y'
);

-- BUILDING CREATE
INSERT INTO XXMPM_API_REGISTRY (
    REGISTRY_ID, ENTITY_NAME, SERVICE_NAME, OPERATION_TYPE, CRED_CODE,
    APIC_ENDPOINT_URL, APIC_API_VERSION, HTTP_METHOD, RECORD_TYPE_HDR, EVENT_CODE_HDR,
    SOURCE_VIEW, SOURCE_KEY_COL, SOURCE_FILTER_COL, JSON_MAPPING_NAME,
    MAX_RETRY_COUNT, TIMEOUT_MINUTES, RETRY_INTERVAL_MINUTES,
    CALLBACK_TARGET_TABLE, CALLBACK_STATUS_COL, CALLBACK_REF_COL, CALLBACK_KEY_COL, IS_ACTIVE
) VALUES (
    103, 'Building', 'XXMPM_CRM_BUILDING_CREATE', 'CREATE', 'MPM_APIC_CRED',
    'https://apiditgateway.adib.co.ae/adib/powerautomate/automations/direct/workflows/BUILDING_WORKFLOW_ID/triggers/manual/paths/invoke',
    '1', 'POST', 'md_building', '100000000',
    'XXMPM_CRM_BUILDING_CREATE_V', 'BUILDING_ID', 'LAST_UPDATE_DATE', 'XXMPM_BUILDING_CREATE_MAPPING',
    3, 30, 10,
    'MPM_BUILDINGS', 'CRM_SYNC_STATUS', 'CRM_REFERENCE_NO', 'BUILDING_ID', 'Y'
);

-- BUILDING UPDATE
INSERT INTO XXMPM_API_REGISTRY (
    REGISTRY_ID, ENTITY_NAME, SERVICE_NAME, OPERATION_TYPE, CRED_CODE,
    APIC_ENDPOINT_URL, APIC_API_VERSION, HTTP_METHOD, RECORD_TYPE_HDR, EVENT_CODE_HDR,
    SOURCE_VIEW, SOURCE_KEY_COL, SOURCE_FILTER_COL, JSON_MAPPING_NAME,
    MAX_RETRY_COUNT, TIMEOUT_MINUTES, RETRY_INTERVAL_MINUTES,
    CALLBACK_TARGET_TABLE, CALLBACK_STATUS_COL, CALLBACK_REF_COL, CALLBACK_KEY_COL, IS_ACTIVE
) VALUES (
    104, 'Building', 'XXMPM_CRM_BUILDING_UPDATE', 'UPDATE', 'MPM_APIC_CRED',
    'https://apiditgateway.adib.co.ae/adib/powerautomate/automations/direct/workflows/BUILDING_WORKFLOW_ID/triggers/manual/paths/invoke',
    '1', 'POST', 'md_building', '100000001',
    'XXMPM_CRM_BUILDING_UPDATE_V', 'BUILDING_ID', 'LAST_UPDATE_DATE', 'XXMPM_BUILDING_UPDATE_MAPPING',
    3, 30, 10,
    'MPM_BUILDINGS', 'CRM_SYNC_STATUS', 'CRM_REFERENCE_NO', 'BUILDING_ID', 'Y'
);

-- FLOOR CREATE
INSERT INTO XXMPM_API_REGISTRY (
    REGISTRY_ID, ENTITY_NAME, SERVICE_NAME, OPERATION_TYPE, CRED_CODE,
    APIC_ENDPOINT_URL, APIC_API_VERSION, HTTP_METHOD, RECORD_TYPE_HDR, EVENT_CODE_HDR,
    SOURCE_VIEW, SOURCE_KEY_COL, SOURCE_FILTER_COL, JSON_MAPPING_NAME,
    MAX_RETRY_COUNT, TIMEOUT_MINUTES, RETRY_INTERVAL_MINUTES,
    CALLBACK_TARGET_TABLE, CALLBACK_STATUS_COL, CALLBACK_REF_COL, CALLBACK_KEY_COL, IS_ACTIVE
) VALUES (
    105, 'Floor', 'XXMPM_CRM_FLOOR_CREATE', 'CREATE', 'MPM_APIC_CRED',
    'https://apiditgateway.adib.co.ae/adib/powerautomate/automations/direct/workflows/FLOOR_WORKFLOW_ID/triggers/manual/paths/invoke',
    '1', 'POST', 'md_floor', '100000000',
    'XXMPM_CRM_FLOOR_CREATE_V', 'FLOOR_ID', 'LAST_UPDATE_DATE', 'XXMPM_FLOOR_CREATE_MAPPING',
    3, 30, 10,
    'MPM_FLOORS', 'CRM_SYNC_STATUS', 'CRM_REFERENCE_NO', 'FLOOR_ID', 'Y'
);

-- FLOOR UPDATE
INSERT INTO XXMPM_API_REGISTRY (
    REGISTRY_ID, ENTITY_NAME, SERVICE_NAME, OPERATION_TYPE, CRED_CODE,
    APIC_ENDPOINT_URL, APIC_API_VERSION, HTTP_METHOD, RECORD_TYPE_HDR, EVENT_CODE_HDR,
    SOURCE_VIEW, SOURCE_KEY_COL, SOURCE_FILTER_COL, JSON_MAPPING_NAME,
    MAX_RETRY_COUNT, TIMEOUT_MINUTES, RETRY_INTERVAL_MINUTES,
    CALLBACK_TARGET_TABLE, CALLBACK_STATUS_COL, CALLBACK_REF_COL, CALLBACK_KEY_COL, IS_ACTIVE
) VALUES (
    106, 'Floor', 'XXMPM_CRM_FLOOR_UPDATE', 'UPDATE', 'MPM_APIC_CRED',
    'https://apiditgateway.adib.co.ae/adib/powerautomate/automations/direct/workflows/FLOOR_WORKFLOW_ID/triggers/manual/paths/invoke',
    '1', 'POST', 'md_floor', '100000001',
    'XXMPM_CRM_FLOOR_UPDATE_V', 'FLOOR_ID', 'LAST_UPDATE_DATE', 'XXMPM_FLOOR_UPDATE_MAPPING',
    3, 30, 10,
    'MPM_FLOORS', 'CRM_SYNC_STATUS', 'CRM_REFERENCE_NO', 'FLOOR_ID', 'Y'
);

-- UNIT CREATE
INSERT INTO XXMPM_API_REGISTRY (
    REGISTRY_ID, ENTITY_NAME, SERVICE_NAME, OPERATION_TYPE, CRED_CODE,
    APIC_ENDPOINT_URL, APIC_API_VERSION, HTTP_METHOD, RECORD_TYPE_HDR, EVENT_CODE_HDR,
    SOURCE_VIEW, SOURCE_KEY_COL, SOURCE_FILTER_COL, JSON_MAPPING_NAME,
    MAX_RETRY_COUNT, TIMEOUT_MINUTES, RETRY_INTERVAL_MINUTES,
    CALLBACK_TARGET_TABLE, CALLBACK_STATUS_COL, CALLBACK_REF_COL, CALLBACK_KEY_COL, IS_ACTIVE
) VALUES (
    107, 'Unit', 'XXMPM_CRM_UNIT_CREATE', 'CREATE', 'MPM_APIC_CRED',
    'https://apiditgateway.adib.co.ae/adib/powerautomate/automations/direct/workflows/UNIT_WORKFLOW_ID/triggers/manual/paths/invoke',
    '1', 'POST', 'md_unit', '100000000',
    'XXMPM_CRM_UNIT_CREATE_V', 'UNIT_ID', 'LAST_UPDATE_DATE', 'XXMPM_UNIT_CREATE_MAPPING',
    3, 30, 10,
    'MPM_UNITS', 'CRM_SYNC_STATUS', 'CRM_REFERENCE_NO', 'UNIT_ID', 'Y'
);

-- UNIT UPDATE
INSERT INTO XXMPM_API_REGISTRY (
    REGISTRY_ID, ENTITY_NAME, SERVICE_NAME, OPERATION_TYPE, CRED_CODE,
    APIC_ENDPOINT_URL, APIC_API_VERSION, HTTP_METHOD, RECORD_TYPE_HDR, EVENT_CODE_HDR,
    SOURCE_VIEW, SOURCE_KEY_COL, SOURCE_FILTER_COL, JSON_MAPPING_NAME,
    MAX_RETRY_COUNT, TIMEOUT_MINUTES, RETRY_INTERVAL_MINUTES,
    CALLBACK_TARGET_TABLE, CALLBACK_STATUS_COL, CALLBACK_REF_COL, CALLBACK_KEY_COL, IS_ACTIVE
) VALUES (
    108, 'Unit', 'XXMPM_CRM_UNIT_UPDATE', 'UPDATE', 'MPM_APIC_CRED',
    'https://apiditgateway.adib.co.ae/adib/powerautomate/automations/direct/workflows/UNIT_WORKFLOW_ID/triggers/manual/paths/invoke',
    '1', 'POST', 'md_unit', '100000001',
    'XXMPM_CRM_UNIT_UPDATE_V', 'UNIT_ID', 'LAST_UPDATE_DATE', 'XXMPM_UNIT_UPDATE_MAPPING',
    3, 30, 10,
    'MPM_UNITS', 'CRM_SYNC_STATUS', 'CRM_REFERENCE_NO', 'UNIT_ID', 'Y'
);

-- UNIT STATUS UPDATE
INSERT INTO XXMPM_API_REGISTRY (
    REGISTRY_ID, ENTITY_NAME, SERVICE_NAME, OPERATION_TYPE, CRED_CODE,
    APIC_ENDPOINT_URL, APIC_API_VERSION, HTTP_METHOD, RECORD_TYPE_HDR, EVENT_CODE_HDR,
    SOURCE_VIEW, SOURCE_KEY_COL, SOURCE_FILTER_COL, JSON_MAPPING_NAME,
    MAX_RETRY_COUNT, TIMEOUT_MINUTES, RETRY_INTERVAL_MINUTES,
    CALLBACK_TARGET_TABLE, CALLBACK_STATUS_COL, CALLBACK_REF_COL, CALLBACK_KEY_COL, IS_ACTIVE
) VALUES (
    109, 'UnitStatus', 'XXMPM_CRM_UNIT_STATUS_UPDATE', 'UPDATE', 'MPM_APIC_CRED',
    'https://apiditgateway.adib.co.ae/adib/powerautomate/automations/direct/workflows/UNIT_STATUS_WORKFLOW_ID/triggers/manual/paths/invoke',
    '1', 'POST', 'md_unit_status', '100000001',
    'XXMPM_CRM_UNIT_STATUS_UPDATE_V', 'UNIT_ID', 'LAST_UPDATE_DATE', 'XXMPM_UNIT_STATUS_UPDATE_MAPPING',
    3, 30, 10,
    'MPM_UNITS', 'CRM_STATUS_SYNC', 'CRM_STATUS_REF', 'UNIT_ID', 'Y'
);
COMMIT;


/* ============================================================================
   TABLE 3: XXMPM_API_FIELD_MAPPING
   Only PROPERTY_CREATE populated below — using ONLY the columns confirmed
   visible in your screenshot. Paste the rest of the columns and I will
   complete the other 8 mappings + remaining PROPERTY_CREATE fields.
   ============================================================================ */
CREATE TABLE XXMPM_API_FIELD_MAPPING (
    MAPPING_ID        NUMBER         GENERATED ALWAYS AS IDENTITY,
    JSON_MAPPING_NAME VARCHAR2(100)  NOT NULL,
    SOURCE_COLUMN     VARCHAR2(128)  NOT NULL,
    JSON_PATH         VARCHAR2(200)  NOT NULL,
    DATA_TYPE         VARCHAR2(20)   DEFAULT 'STRING',
    DATE_FORMAT       VARCHAR2(50),
    IS_MANDATORY      VARCHAR2(1)    DEFAULT 'N',
    DISPLAY_ORDER     NUMBER         DEFAULT 10,
    IS_ACTIVE         VARCHAR2(1)    DEFAULT 'Y',
    CONSTRAINT PK_XXMPM_FIELD_MAP PRIMARY KEY (MAPPING_ID)
);
CREATE INDEX IX_XXMPM_FIELD_MAP_NAME ON XXMPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, IS_ACTIVE);

-- XXMPM_PROPERTY_CREATE_MAPPING
-- Only columns CONFIRMED in your screenshot. NOTE: UNIQUE_ID excluded from
-- payload (internal Oracle identifier, not part of CRM contract) — remove
-- this comment and add a row if CRM actually needs unique_id in the JSON.
INSERT INTO XXMPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES
  ('XXMPM_PROPERTY_CREATE_MAPPING', 'PROPERTY_ID',   'property_id',        'STRING', 10, 'Y');
INSERT INTO XXMPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES
  ('XXMPM_PROPERTY_CREATE_MAPPING', 'PROPERTY_NAME', 'property_name',      'STRING', 20, 'Y');
INSERT INTO XXMPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES
  ('XXMPM_PROPERTY_CREATE_MAPPING', 'PROPERTY_CODE', 'property_code',      'STRING', 30, 'Y');
INSERT INTO XXMPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES
  ('XXMPM_PROPERTY_CREATE_MAPPING', 'REGION_ID',     'region.region_id',   'STRING', 40, 'Y');
INSERT INTO XXMPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES
  ('XXMPM_PROPERTY_CREATE_MAPPING', 'REGION_NAME',   'region.region_name', 'STRING', 50, 'Y');
INSERT INTO XXMPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES
  ('XXMPM_PROPERTY_CREATE_MAPPING', 'CITY_ID',       'city.city_id',       'STRING', 60, 'Y');
INSERT INTO XXMPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES
  ('XXMPM_PROPERTY_CREATE_MAPPING', 'CITY_NAME',     'city.city_name',     'STRING', 70, 'Y');
COMMIT;

-- ── PLACEHOLDER — paste remaining PROPERTY_CREATE_V columns here ───────────
-- Pattern to follow for each additional column:
-- INSERT INTO XXMPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES
--   ('XXMPM_PROPERTY_CREATE_MAPPING', '<COLUMN_NAME>', '<json_path>', 'STRING', <order>, 'Y');

-- ── PLACEHOLDER — XXMPM_PROPERTY_UPDATE_MAPPING (paste column list) ────────
-- ── PLACEHOLDER — XXMPM_BUILDING_CREATE_MAPPING (paste column list) ────────
-- ── PLACEHOLDER — XXMPM_BUILDING_UPDATE_MAPPING (paste column list) ────────
-- ── PLACEHOLDER — XXMPM_FLOOR_CREATE_MAPPING    (paste column list) ────────
-- ── PLACEHOLDER — XXMPM_FLOOR_UPDATE_MAPPING    (paste column list) ────────
-- ── PLACEHOLDER — XXMPM_UNIT_CREATE_MAPPING     (paste column list) ────────
-- ── PLACEHOLDER — XXMPM_UNIT_UPDATE_MAPPING     (paste column list) ────────
-- ── PLACEHOLDER — XXMPM_UNIT_STATUS_UPDATE_MAPPING (paste column list) ─────


/* ============================================================================
   TABLE 4: XXMPM_API_WATERMARK — one row per SERVICE_NAME
   Keyed by SERVICE_NAME (not REGISTRY_ID) — matches existing table structure.
   ============================================================================ */
CREATE TABLE XXMPM_API_WATERMARK (
    SERVICE_NAME       VARCHAR2(100) NOT NULL,
    LAST_PROCESSED_TS  TIMESTAMP     DEFAULT TIMESTAMP '2000-01-01 00:00:00',
    LAST_RUN_STATUS    VARCHAR2(100),
    LAST_RUN_RECORDS   NUMBER        DEFAULT 0,
    UPDATED_DATE       TIMESTAMP,
    CONSTRAINT PK_XXMPM_WATERMARK PRIMARY KEY (SERVICE_NAME),
    CONSTRAINT FK_XXMPM_WM_REG FOREIGN KEY (SERVICE_NAME)
        REFERENCES XXMPM_API_REGISTRY(SERVICE_NAME)
);

INSERT INTO XXMPM_API_WATERMARK (SERVICE_NAME, LAST_PROCESSED_TS)
SELECT SERVICE_NAME, TIMESTAMP '2000-01-01 00:00:00'
FROM XXMPM_API_REGISTRY;
COMMIT;


/* ============================================================================
   TABLE 5: XXMPM_CRM_INTEGRATION_LOG — full audit trail
   ============================================================================ */
CREATE TABLE XXMPM_CRM_INTEGRATION_LOG (
    LOG_ID               NUMBER         GENERATED ALWAYS AS IDENTITY,
    REGISTRY_ID          NUMBER         NOT NULL,
    ENTITY_NAME          VARCHAR2(100),
    OPERATION_TYPE       VARCHAR2(20),
    SOURCE_RECORD_ID     VARCHAR2(200)  NOT NULL,
    TRANSACTION_GROUP_ID VARCHAR2(40),
    ATTEMPT_NO           NUMBER         DEFAULT 1,
    REQUEST_PAYLOAD      CLOB,
    SENT_DATE            TIMESTAMP,
    HTTP_STATUS_CODE     VARCHAR2(10),
    ACK_RESPONSE         CLOB,
    ACK_REQUEST_ID       VARCHAR2(100),
    ACK_STATUS_CODE      VARCHAR2(10),
    ACK_DESCRIPTION      VARCHAR2(500),
    FINAL_STATUS         VARCHAR2(30)   DEFAULT 'PENDING',
    ERROR_CODE           VARCHAR2(50),
    ERROR_MESSAGE        VARCHAR2(4000),
    CRM_ENTITY_ID        VARCHAR2(200),
    CRM_REFERENCE_NO     VARCHAR2(200),
    CALLBACK_PAYLOAD     CLOB,
    CALLBACK_DATE        TIMESTAMP,
    CALLBACK_RESULT_CODE VARCHAR2(50),
    CALLBACK_RESULT_DESC VARCHAR2(500),
    CALLBACK_VALID_ERRORS CLOB,
    RETRY_COUNT          NUMBER         DEFAULT 0,
    NEXT_RETRY_DATE      TIMESTAMP,
    IS_FINAL_ATTEMPT     VARCHAR2(1)    DEFAULT 'N',
    CREATED_DATE         TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_DATE         TIMESTAMP,
    CONSTRAINT PK_XXMPM_INTG_LOG PRIMARY KEY (LOG_ID)
);
CREATE INDEX IX_XXMPM_LOG_REG_REC ON XXMPM_CRM_INTEGRATION_LOG (REGISTRY_ID, SOURCE_RECORD_ID);
CREATE INDEX IX_XXMPM_LOG_STATUS  ON XXMPM_CRM_INTEGRATION_LOG (FINAL_STATUS, REGISTRY_ID);
CREATE INDEX IX_XXMPM_LOG_TXNGRP  ON XXMPM_CRM_INTEGRATION_LOG (TRANSACTION_GROUP_ID);
CREATE INDEX IX_XXMPM_LOG_REQID   ON XXMPM_CRM_INTEGRATION_LOG (ACK_REQUEST_ID);


/* ============================================================================
   TABLE 6: XXMPM_JOB_RUN_HISTORY
   ============================================================================ */
CREATE TABLE XXMPM_JOB_RUN_HISTORY (
    RUN_ID            NUMBER         GENERATED ALWAYS AS IDENTITY,
    JOB_NAME          VARCHAR2(60)   NOT NULL,
    STATUS            VARCHAR2(20)   DEFAULT 'RUNNING',
    START_TIME        TIMESTAMP      DEFAULT SYSTIMESTAMP,
    END_TIME          TIMESTAMP,
    RECORDS_PROCESSED NUMBER         DEFAULT 0,
    RECORDS_SUCCESS   NUMBER         DEFAULT 0,
    RECORDS_FAILED    NUMBER         DEFAULT 0,
    ERROR_MESSAGE     VARCHAR2(4000),
    CONSTRAINT PK_XXMPM_JOB_HIST PRIMARY KEY (RUN_ID)
);


/* ============================================================================
   TABLE 7: XXMPM_ERROR_CODE_MASTER
   ============================================================================ */
CREATE TABLE XXMPM_ERROR_CODE_MASTER (
    ERROR_CODE        VARCHAR2(50)   NOT NULL,
    ERROR_CATEGORY    VARCHAR2(50),
    DESCRIPTION       VARCHAR2(500),
    IS_RETRYABLE      VARCHAR2(1)    DEFAULT 'N',
    IS_ACTIVE         VARCHAR2(1)    DEFAULT 'Y',
    CONSTRAINT PK_XXMPM_ERR_MASTER PRIMARY KEY (ERROR_CODE)
);

INSERT INTO XXMPM_ERROR_CODE_MASTER VALUES ('SUCCESS',          'SUCCESS',        'Record processed successfully in D365',                    'N','Y');
INSERT INTO XXMPM_ERROR_CODE_MASTER VALUES ('VALIDATION_FAILED','BUSINESS_ERROR', 'CRM business rule validation failed',                      'N','Y');
INSERT INTO XXMPM_ERROR_CODE_MASTER VALUES ('RECORD_NOT_FOUND', 'BUSINESS_ERROR', 'Target record not found in D365',                          'N','Y');
INSERT INTO XXMPM_ERROR_CODE_MASTER VALUES ('DUPLICATE_RECORD', 'BUSINESS_ERROR', 'Record already exists in D365',                            'N','Y');
INSERT INTO XXMPM_ERROR_CODE_MASTER VALUES ('UNKNOWN_ERROR',    'SYSTEM_ERROR',   'Unexpected error from CRM',                                'Y','Y');
INSERT INTO XXMPM_ERROR_CODE_MASTER VALUES ('CONN_FAILED',      'SYSTEM_ERROR',   'Network connection or timeout to APIC',                    'Y','Y');
INSERT INTO XXMPM_ERROR_CODE_MASTER VALUES ('AUTH_FAILED',      'SYSTEM_ERROR',   'Bearer token rejected by APIC',                            'Y','Y');
INSERT INTO XXMPM_ERROR_CODE_MASTER VALUES ('TIMEOUT',          'SYSTEM_ERROR',   'No callback received within timeout window',              'Y','Y');
INSERT INTO XXMPM_ERROR_CODE_MASTER VALUES ('EXHAUSTED',        'SYSTEM_ERROR',   'Maximum retry attempts reached, manual intervention needed','N','Y');
COMMIT;


/* ============================================================================
   VIEW 1: XXMPM_V_TIMEOUT_CANDIDATES
   ============================================================================ */
CREATE OR REPLACE VIEW XXMPM_V_TIMEOUT_CANDIDATES AS
SELECT
    L.LOG_ID, L.REGISTRY_ID, L.SOURCE_RECORD_ID, L.TRANSACTION_GROUP_ID,
    L.ATTEMPT_NO, L.RETRY_COUNT, L.SENT_DATE, L.FINAL_STATUS
FROM XXMPM_CRM_INTEGRATION_LOG L
JOIN XXMPM_API_REGISTRY         R ON R.REGISTRY_ID = L.REGISTRY_ID
WHERE L.FINAL_STATUS IN ('SENT', 'PENDING')
  AND L.SENT_DATE    < SYSTIMESTAMP - (R.TIMEOUT_MINUTES / 1440)
  AND R.IS_ACTIVE    = 'Y';


/* ============================================================================
   VIEW 2: XXMPM_V_PENDING_RETRY
   ============================================================================ */
CREATE OR REPLACE VIEW XXMPM_V_PENDING_RETRY AS
SELECT
    L.LOG_ID, L.REGISTRY_ID, L.SOURCE_RECORD_ID, L.TRANSACTION_GROUP_ID,
    L.ATTEMPT_NO, L.RETRY_COUNT, R.MAX_RETRY_COUNT, R.RETRY_INTERVAL_MINUTES,
    L.FINAL_STATUS
FROM XXMPM_CRM_INTEGRATION_LOG L
JOIN XXMPM_API_REGISTRY         R ON R.REGISTRY_ID = L.REGISTRY_ID
WHERE L.FINAL_STATUS   IN ('FAILED', 'TIMEOUT')
  AND L.RETRY_COUNT    <  R.MAX_RETRY_COUNT
  AND (L.NEXT_RETRY_DATE IS NULL OR L.NEXT_RETRY_DATE <= SYSTIMESTAMP)
  AND L.IS_FINAL_ATTEMPT = 'N'
  AND R.IS_ACTIVE        = 'Y';


PROMPT ============================================================
PROMPT  Tables created with REAL view names from your environment.
PROMPT  9 registries seeded: Property, Building, Floor, Unit (x2),
PROMPT  Unit Status — matching XXMPM_CRM_*_V views exactly.
PROMPT
PROMPT  NEXT STEP: Paste the full column list for each view and I
PROMPT  will complete all 9 field mapping sets (currently only
PROMPT  7 columns done for PROPERTY_CREATE).
PROMPT ============================================================
