-- =============================================================================
-- ADIB MPM PROPERTIES -- CRM xRM INTEGRATION
-- SIT FULL DATA INSERT -- NON PRODUCTION ONLY
-- Author  : Tajudeen Jalaudin -- Senior Solution Architect, ADIB
-- Date    : 24 September 2026
-- WARNING : NON PRODUCTION ONLY -- contains real SIT credentials
--           DO NOT run in UAT or PROD
--           DO NOT commit real credentials to production branch
-- Run AFTER: SIT_DEPLOYMENT_COMPLETE.sql
-- =============================================================================

SET DEFINE OFF
SET SERVEROUTPUT ON SIZE UNLIMITED

PROMPT
PROMPT =============================================================
PROMPT   SIT FULL DATA INSERT -- NON PRODUCTION ONLY
PROMPT =============================================================
PROMPT

-- =============================================================================
-- SECTION 1: CREDENTIALS (SIT values)
-- =============================================================================
PROMPT --- SECTION 1: CREDENTIALS ---

DELETE FROM CRM_MPM_API_CREDENTIALS;
COMMIT;

INSERT INTO CRM_MPM_API_CREDENTIALS (
    CRED_CODE, TOKEN_URL, CLIENT_ID, CLIENT_SECRET_REF,
    GRANT_TYPE, SCOPE,
    WALLET_PATH, WALLET_PASSWORD,
    IS_ACTIVE, CREATED_DATE)
VALUES (
    'APIC_PXRM',
    'https://apisitgatewaylb.adib.co.ae:443/adib/oauth-client/oauth2/token',
    'bdbd7c57145bcbaaf4e81bdc16181287',
    'cb9ed345fcc99e9c165049a6f608ee5b',
    'client_credentials',
    'powerapp:access',
    '/u01/app/oracle/product/19.0.0/db_1/wallet/sit',
    'WalletPassw0rd',
    'Y', SYSTIMESTAMP);
COMMIT;
DBMS_OUTPUT.PUT_LINE('Done: CRM_MPM_API_CREDENTIALS');

PROMPT --- SECTION 1 COMPLETE ---
PROMPT

-- =============================================================================
-- SECTION 2: SERVICE REGISTRY (9 services)
-- =============================================================================
PROMPT --- SECTION 2: SERVICE REGISTRY ---

DELETE FROM CRM_MPM_API_WATERMARK;
DELETE FROM CRM_MPM_CRM_INTEGRATION_LOG;
DELETE FROM CRM_MPM_API_REGISTRY;
COMMIT;

DECLARE
    v_id NUMBER;

    PROCEDURE ins_reg(
        p_svc   VARCHAR2, p_entity VARCHAR2, p_op VARCHAR2,
        p_view  VARCHAR2, p_key   VARCHAR2, p_map  VARCHAR2,
        p_url   VARCHAR2, p_rtype VARCHAR2, p_evt  VARCHAR2,
        p_ord   NUMBER)
    IS
    BEGIN
        INSERT INTO CRM_MPM_API_REGISTRY (
            SERVICE_NAME, ENTITY_NAME, OPERATION_TYPE,
            SOURCE_TYPE, SOURCE_VIEW, SOURCE_KEY_COL,
            JSON_MAPPING_NAME, APIC_ENDPOINT_URL,
            APIC_API_VERSION, RECORD_TYPE_HDR, EVENT_CODE_HDR,
            HTTP_METHOD, CRED_CODE,
            EXECUTION_ORDER, BATCH_SIZE,
            MAX_RETRY_COUNT, RETRY_INTERVAL_MINUTES,
            TIMEOUT_MINUTES, IS_ACTIVE)
        VALUES (
            p_svc, p_entity, p_op,
            'VIEW', p_view, p_key,
            p_map, p_url,
            '1', p_rtype, p_evt,
            'POST', 'APIC_PXRM',
            p_ord, 100,
            3, 30,
            60, 'Y')
        RETURNING REGISTRY_ID INTO v_id;
        DBMS_OUTPUT.PUT_LINE('Registry: '||p_svc||' ID='||v_id);
    END;

    v_url VARCHAR2(500) :=
        'https://apisitgatewaylb.adib.co.ae:443/adib/powerautomate/automations/direct/workflows/e287bb6987cc4254bfbaa954d3fd4954/triggers/manual/paths/invoke';
BEGIN
    ins_reg('MD_PROJECT_CREATE',  'Property',    'CREATE',
            'XXMPM_CRM_PROPERTY_CREATE_V',    'PROPERTY_ID',
            'XXMPM_CRM_PROPERTY_CREATE_V',    v_url,
            'md_project',    '100000000', 10);

    ins_reg('MD_PROJECT_UPDATE',  'Property',    'UPDATE',
            'XXMPM_CRM_PROPERTY_UPDATE_V',    'PROPERTY_ID',
            'XXMPM_CRM_PROPERTY_UPDATE_V',    v_url,
            'md_project',    '100000001', 20);

    ins_reg('MD_BUILDING_CREATE', 'Building',    'CREATE',
            'XXMPM_CRM_BUILDING_CREATE_V',    'BUILDING_ID',
            'XXMPM_CRM_BUILDING_CREATE_V',    v_url,
            'md_building',   '100000000', 30);

    ins_reg('MD_BUILDING_UPDATE', 'Building',    'UPDATE',
            'XXMPM_CRM_BUILDING_UPDATE_V',    'BUILDING_ID',
            'XXMPM_CRM_BUILDING_UPDATE_V',    v_url,
            'md_building',   '100000001', 40);

    ins_reg('MD_FLOOR_CREATE',    'Floor',       'CREATE',
            'XXMPM_CRM_FLOOR_CREATE_V',       'FLOOR_ID',
            'XXMPM_CRM_FLOOR_CREATE_V',       v_url,
            'md_floor',      '100000000', 50);

    ins_reg('MD_FLOOR_UPDATE',    'Floor',       'UPDATE',
            'XXMPM_CRM_FLOOR_UPDATE_V',       'FLOOR_ID',
            'XXMPM_CRM_FLOOR_UPDATE_V',       v_url,
            'md_floor',      '100000001', 60);

    ins_reg('MD_UNIT_CREATE',     'Unit',        'CREATE',
            'XXMPM_CRM_UNIT_CREATE_V',        'UNIT_ID',
            'XXMPM_CRM_UNIT_CREATE_V',        v_url,
            'md_unit',       '100000000', 70);

    ins_reg('MD_UNIT_UPDATE',     'Unit',        'UPDATE',
            'XXMPM_CRM_UNIT_UPDATE_V',        'UNIT_ID',
            'XXMPM_CRM_UNIT_UPDATE_V',        v_url,
            'md_unit',       '100000001', 80);

    ins_reg('MD_UNIT_STATUS_UPDATE','Unit Status','UPDATE',
            'XXMPM_CRM_UNIT_STATUS_V',        'UNIT_ID',
            'XXMPM_CRM_UNIT_STATUS_V',        v_url,
            'md_unit',       '100000001', 90);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Done: 9 services inserted');
END;
/

PROMPT --- SECTION 2 COMPLETE ---
PROMPT

-- =============================================================================
-- SECTION 3: FIELD MAPPINGS
-- =============================================================================
PROMPT --- SECTION 3: FIELD MAPPINGS ---

DELETE FROM CRM_MPM_API_FIELD_MAPPING;
COMMIT;

INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'PROPERTY_ID', 'property_id', 'STRING', 10, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'PROPERTY_NAME', 'property_name', 'STRING', 20, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'PROPERTY_CODE', 'property_code', 'STRING', 30, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'REGION_ID', 'region.region_id', 'STRING', 40, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'REGION_NAME', 'region.region_name', 'STRING', 50, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'CITY_ID', 'city.city_id', 'STRING', 60, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'CITY_NAME', 'city.city_name', 'STRING', 70, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'AREA_ID', 'area.area_id', 'STRING', 80, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'AREA_NAME', 'area.area_name', 'STRING', 90, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'SECTOR_ID', 'sector.sector_id', 'STRING', 100, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'SECTOR_NAME', 'sector.sector_name', 'STRING', 110, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'PLOT_ID', 'plot.plot_id', 'STRING', 120, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'PLOT_NAME', 'plot.plot_name', 'STRING', 130, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'COUNTRY_CODE', 'country.country_code', 'STRING', 140, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'COUNTRY_NAME', 'country.country_name', 'STRING', 150, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'DESCRIPTION', 'description', 'STRING', 160, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'TENURE', 'tenure.tenure_id', 'STRING', 170, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'TENURE_NAME', 'tenure.tenure_name', 'STRING', 180, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'PROPERTY_TYPE', 'property_type.type_id', 'STRING', 190, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'PROPERTY_TYPE_NAME', 'property_type.type_name', 'STRING', 200, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'STATUS_ID', 'status.status_id', 'STRING', 210, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'STATUS_NAME', 'status.status_name', 'STRING', 220, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'CLIENT', 'client.client_code', 'STRING', 230, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'CLIENT_NAME', 'client.client_name', 'STRING', 240, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'CLIENT_ID', 'client.client_id', 'STRING', 250, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'ACTIVE_PROPERTY', 'active_property', 'STRING', 260, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'PROPERTY_GRADE', 'property_grade', 'STRING', 270, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_CREATE_V', 'ORG_ID', 'org_id', 'STRING', 280, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'PROPERTY_ID', 'property_id', 'STRING', 10, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'PROPERTY_NAME', 'property_name', 'STRING', 20, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'PROPERTY_CODE', 'property_code', 'STRING', 30, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'CITY_ID', 'city.city_id', 'STRING', 40, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'CITY_NAME', 'city.city_name', 'STRING', 50, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'AREA_ID', 'area.area_id', 'STRING', 60, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'AREA_NAME', 'area.area_name', 'STRING', 70, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'SECTOR_ID', 'sector.sector_id', 'STRING', 80, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'SECTOR_NAME', 'sector.sector_name', 'STRING', 90, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'PLOT_ID', 'plot.plot_id', 'STRING', 100, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'PLOT_NAME', 'plot.plot_name', 'STRING', 110, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'DESCRIPTION', 'description', 'STRING', 120, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'TENURE', 'tenure.tenure_id', 'STRING', 130, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'TENURE_NAME', 'tenure.tenure_name', 'STRING', 140, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'PROPERTY_TYPE', 'property_type.type_id', 'STRING', 150, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'PROPERTY_TYPE_NAME', 'property_type.type_name', 'STRING', 160, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'STATUS_ID', 'status.status_id', 'STRING', 170, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'STATUS_NAME', 'status.status_name', 'STRING', 180, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'CLIENT', 'client.client_code', 'STRING', 190, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'CLIENT_NAME', 'client.client_name', 'STRING', 200, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'CLIENT_ID', 'client.client_id', 'STRING', 210, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'ACTIVE_PROPERTY', 'active_property', 'STRING', 220, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_PROPERTY_UPDATE_V', 'PROPERTY_GRADE', 'property_grade', 'STRING', 230, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'BUILDING_ID', 'building_id', 'STRING', 10, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'LOCATION_TYPE', 'location_type', 'STRING', 20, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'BUILDING_CODE', 'building_code', 'STRING', 30, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'BUILDING_ALIAS', 'building_alias', 'STRING', 40, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'BUILDING_NAME', 'building_name', 'STRING', 50, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'LEASE_OR_OWNED', 'lease_or_owned', 'STRING', 60, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'COUNTRY_ID', 'country.country_id', 'STRING', 70, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'COUNTRY', 'country.country_name', 'STRING', 80, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'STATE', 'state', 'STRING', 90, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'ADDRESS_LINE_1', 'address.line_1', 'STRING', 100, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'ADDRESS_LINE_2', 'address.line_2', 'STRING', 110, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'ADDRESS_LINE_3', 'address.line_3', 'STRING', 120, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'ADDRESS_LINE_4', 'address.line_4', 'STRING', 130, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'GPS', 'gps', 'STRING', 140, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'POSTAL_CODE', 'postal_code', 'STRING', 150, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'MAX_CAPACITY', 'max_capacity', 'STRING', 160, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'OPTIMUM_CAPACITY', 'optimum_capacity', 'STRING', 170, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'RENTABLE_AREA', 'rentable_area', 'STRING', 180, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'USABLE_AREA', 'usable_area', 'STRING', 190, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'UOM', 'uom', 'STRING', 200, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'STATUS', 'status', 'STRING', 210, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'OWNER_NAME', 'owner_name', 'STRING', 220, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'BUILDING_NAME_ARABIC', 'building_name_arabic', 'STRING', 230, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'BUILDING_NO_ARABIC', 'building_no_arabic', 'STRING', 240, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'STREET_NO_ARABIC', 'street_no_arabic', 'STRING', 250, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'CITY_ARABIC', 'city_arabic', 'STRING', 260, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'AGE_OF_BUILDING', 'age_of_building', 'STRING', 270, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'BUILT_UP_AREA', 'built_up_area', 'STRING', 280, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'MUNICIPALITY_PMA_ID', 'municipality_pma_id', 'STRING', 290, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'MUNICIPALITY_BLDG_ID', 'municipality_bldg_id', 'STRING', 300, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'BASEMENT_PARKING', 'basement_parking', 'STRING', 310, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'TAKE_OVER_NO', 'take_over_no', 'STRING', 320, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'PURPOSE', 'purpose', 'STRING', 330, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'LICENSE_NO', 'license_no', 'STRING', 340, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'LEGAL_ENTITY', 'legal_entity', 'STRING', 350, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'PROPERTY_ID', 'property_id', 'STRING', 360, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'BUILDING_TYPE', 'building_type', 'STRING', 370, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'GROSS_AREA', 'gross_area', 'STRING', 380, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'ASSIGNABLE_AREA', 'assignable_area', 'STRING', 390, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'COMMON_AREA', 'common_area', 'STRING', 400, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'ACTIVE_START_DATE', 'active_start_date', 'STRING', 410, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'ACTIVE_END_DATE', 'active_end_date', 'STRING', 420, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_CREATE_V', 'OCCUPANCY_STATUS', 'occupancy_status', 'STRING', 430, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'BUILDING_NAME', 'building_name', 'STRING', 10, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'LEASE_OR_OWNED', 'lease_or_owned', 'STRING', 20, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'COUNTRY_ID', 'country.country_id', 'STRING', 30, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'STATE', 'state', 'STRING', 40, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'GPS', 'gps', 'STRING', 50, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'POSTAL_CODE', 'postal_code', 'STRING', 60, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'STATUS', 'status', 'STRING', 70, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'OWNER_NAME', 'owner_name', 'STRING', 80, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'BUILDING_NAME_ARABIC', 'building_name_arabic', 'STRING', 90, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'BUILDING_NO_ARABIC', 'building_no_arabic', 'STRING', 100, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'STREET_NO_ARABIC', 'street_no_arabic', 'STRING', 110, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'CITY_ARABIC', 'city_arabic', 'STRING', 120, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'AGE_OF_BUILDING', 'age_of_building', 'STRING', 130, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'BUILT_UP_AREA', 'built_up_area', 'STRING', 140, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'MUNICIPALITY_PMA_ID', 'municipality_pma_id', 'STRING', 150, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'MUNICIPALITY_BLDG_ID', 'municipality_bldg_id', 'STRING', 160, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'BASEMENT_PARKING', 'basement_parking', 'STRING', 170, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'TAKE_OVER_NO', 'take_over_no', 'STRING', 180, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'PURPOSE', 'purpose', 'STRING', 190, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'LICENSE_NO', 'license_no', 'STRING', 200, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'ACTIVE_START_DATE', 'active_start_date', 'STRING', 210, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'ACTIVE_END_DATE', 'active_end_date', 'STRING', 220, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'OCCUPANCY_STATUS', 'occupancy_status', 'STRING', 230, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'CONTEXT_VALUE', 'context_value', 'STRING', 240, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'INSURANCE_POLICY_NO', 'insurance.policy_no', 'STRING', 250, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'INSURACE_EXPIRY_DATE', 'insurance.expiry_date', 'STRING', 260, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'INSURANCE_SUM_ASSURED', 'insurance.sum_assured', 'STRING', 270, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'OPERATIONS_MANAGER', 'operations_manager', 'STRING', 280, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'FM_ENGINEER', 'fm_engineer', 'STRING', 290, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'LEASING_AGENT', 'leasing_agent', 'STRING', 300, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_BUILDING_UPDATE_V', 'RELATIONS_MANAGER', 'relations_manager', 'STRING', 310, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'FLOOR_ID', 'floor_id', 'STRING', 10, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'LOCATION_TYPE', 'location_type', 'STRING', 20, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'FLOOR_CODE', 'floor_code', 'STRING', 30, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'FLOOR_ALIAS', 'floor_alias', 'STRING', 40, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'FLOOR', 'floor_number', 'STRING', 50, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'LEASE_OR_OWNED', 'lease_or_owned', 'STRING', 60, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'RENTABLE_AREA', 'rentable_area', 'STRING', 70, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'USABLE_AREA', 'usable_area', 'STRING', 80, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'UOM', 'uom', 'STRING', 90, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'STATUS', 'status', 'STRING', 100, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'LEGAL_ENTITY', 'legal_entity', 'STRING', 110, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'PARENT_LOCATION_ID', 'parent_location_id', 'STRING', 120, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'ASSIGNABLE_AREA', 'assignable_area', 'STRING', 130, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'ACTIVE_START_DATE', 'active_start_date', 'STRING', 140, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'ACTIVE_END_DATE', 'active_end_date', 'STRING', 150, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_CREATE_V', 'OCCUPANCY_STATUS', 'occupancy_status', 'STRING', 160, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_UPDATE_V', 'FLOOR_ID', 'floor_id', 'STRING', 10, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_UPDATE_V', 'LOCATION_TYPE', 'location_type', 'STRING', 20, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_UPDATE_V', 'FLOOR_CODE', 'floor_code', 'STRING', 30, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_UPDATE_V', 'FLOOR', 'floor_number', 'STRING', 40, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_UPDATE_V', 'LEASE_OR_OWNED', 'lease_or_owned', 'STRING', 50, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_UPDATE_V', 'STATUS', 'status', 'STRING', 60, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_UPDATE_V', 'ACTIVE_START_DATE', 'active_start_date', 'STRING', 70, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_UPDATE_V', 'ACTIVE_END_DATE', 'active_end_date', 'STRING', 80, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_FLOOR_UPDATE_V', 'OCCUPANCY_STATUS', 'occupancy_status', 'STRING', 90, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'UNIT_ID', 'unit_id', 'STRING', 10, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'LOCATION_TYPE', 'location_type', 'STRING', 20, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'UNIT_CODE', 'unit_code', 'STRING', 30, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'UNIT_ALIAS', 'unit_alias', 'STRING', 40, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'BUILDING_NAME', 'building_name', 'STRING', 50, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'LEASE_OR_OWNED', 'lease_or_owned', 'STRING', 60, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'UOM', 'uom', 'STRING', 70, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'GROSS_AREA', 'gross_area', 'STRING', 80, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'RENTABLE_AREA', 'rentable_area', 'STRING', 90, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'USABLE_AREA', 'usable_area', 'STRING', 100, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'ASSIGNABLE_AREA', 'assignable_area', 'STRING', 110, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'COMMON_AREA', 'common_area', 'STRING', 120, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'STATUS', 'status', 'STRING', 130, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'SPACE_TYPE', 'space_type', 'STRING', 140, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'STYLE', 'style', 'STRING', 150, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'MAID_ROOM', 'maid_room', 'STRING', 160, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'PARKING1', 'parking1', 'STRING', 170, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'UNIT_GRADE', 'unit_grade', 'STRING', 180, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'DRIVER_ROOM', 'driver_room', 'STRING', 190, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'VILLA_ENTRANCE', 'villa_entrance', 'STRING', 200, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'AC_TYPE', 'ac_type', 'STRING', 210, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'BALCONY', 'balcony', 'STRING', 220, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'UNIT_VIEW', 'unit_view', 'STRING', 230, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'MAINTAIN_BY_MPM', 'maintain_by_mpm', 'STRING', 240, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'TAKEOVER_NUMBER', 'takeover_number', 'STRING', 250, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'OWNER_NAME', 'owner_name', 'STRING', 260, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'UNIT_STATUS', 'unit_status', 'STRING', 270, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'LEGAL_ENTITY', 'legal_entity', 'STRING', 280, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'FLOOR_ID', 'floor_id', 'STRING', 290, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'UNIT_TYPE', 'unit_type', 'STRING', 300, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'FUNCTION_TYPE', 'function_type', 'STRING', 310, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'STANDARD_TYPE', 'standard_type', 'STRING', 320, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'ACTIVE_START_DATE', 'active_start_date', 'STRING', 330, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'ACTIVE_END_DATE', 'active_end_date', 'STRING', 340, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_CREATE_V', 'OCCUPANCY_STATUS', 'occupancy_status', 'STRING', 350, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'UNIT_ID', 'unit_id', 'STRING', 10, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'UNIT_CODE', 'unit_code', 'STRING', 20, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'LEASE_OR_OWNED', 'lease_or_owned', 'STRING', 30, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'GROSS_AREA', 'gross_area', 'STRING', 40, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'RENTABLE_AREA', 'rentable_area', 'STRING', 50, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'USABLE_AREA', 'usable_area', 'STRING', 60, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'ASSIGNABLE_AREA', 'assignable_area', 'STRING', 70, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'COMMON_AREA', 'common_area', 'STRING', 80, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'UOM', 'uom', 'STRING', 90, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'STATUS', 'status', 'STRING', 100, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'SPACE_TYPE', 'space_type', 'STRING', 110, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'ATTRIBUTE_CATEGORY', 'attribute_category', 'STRING', 120, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'STYLE', 'style', 'STRING', 130, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'MAID_ROOM', 'maid_room', 'STRING', 140, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'PARKING1', 'parking1', 'STRING', 150, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'UNIT_GRADE', 'unit_grade', 'STRING', 160, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'DRIVER_ROOM', 'driver_room', 'STRING', 170, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'VILLA_ENTRANCE', 'villa_entrance', 'STRING', 180, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'AC_TYPE', 'ac_type', 'STRING', 190, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'BALCONY', 'balcony', 'STRING', 200, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'UNIT_VIEW', 'unit_view', 'STRING', 210, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'MAINTAIN_BY_MPM', 'maintain_by_mpm', 'STRING', 220, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'TAKEOVER_NUMBER', 'takeover_number', 'STRING', 230, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'OWNER_NAME', 'owner_name', 'STRING', 240, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'UNIT_STATUS', 'unit_status', 'STRING', 250, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'UNIT_TYPE', 'unit_type', 'STRING', 260, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'FUNCTION_TYPE', 'function_type', 'STRING', 270, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'STANDARD_TYPE', 'standard_type', 'STRING', 280, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'ACTIVE_START_DATE', 'active_start_date', 'STRING', 290, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'ACTIVE_END_DATE', 'active_end_date', 'STRING', 300, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'OCCUPANCY_STATUS', 'occupancy_status', 'STRING', 310, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_UPDATE_V', 'TENANT', 'tenant', 'STRING', 320, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_STATUS_UPDATE_V', 'UNIT_ID', 'unit_id', 'STRING', 10, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_STATUS_UPDATE_V', 'UNIT_CODE', 'unit_code', 'STRING', 20, 'Y');
INSERT INTO CRM_MPM_API_FIELD_MAPPING (JSON_MAPPING_NAME, SOURCE_COLUMN, JSON_PATH, DATA_TYPE, DISPLAY_ORDER, IS_ACTIVE) VALUES ('XXMPM_CRM_UNIT_STATUS_UPDATE_V', 'UNIT_STATUS', 'status_code', 'STRING', 30, 'Y');

COMMIT;
DBMS_OUTPUT.PUT_LINE('Done: Field mappings loaded');

PROMPT --- SECTION 3 COMPLETE ---
PROMPT

-- =============================================================================
-- SECTION 4: WATERMARK (one row per service, start from yesterday)
-- =============================================================================
PROMPT --- SECTION 4: WATERMARK ---

INSERT INTO CRM_MPM_API_WATERMARK
    (REGISTRY_ID, LAST_PROCESSED_TS, LAST_RUN_STATUS, LAST_RUN_RECORDS, UPDATED_DATE)
SELECT REGISTRY_ID, SYSDATE - 1, 'INIT', 0, SYSTIMESTAMP
FROM   CRM_MPM_API_REGISTRY;
COMMIT;
DBMS_OUTPUT.PUT_LINE('Done: Watermark initialised');

PROMPT --- SECTION 4 COMPLETE ---
PROMPT

-- =============================================================================
-- SECTION 5: INTEGRATION LOG -- sample records for Monitor tab testing
-- Covers all status types so all tabs show data immediately
-- =============================================================================
PROMPT --- SECTION 5: INTEGRATION LOG (sample data) ---

DELETE FROM CRM_MPM_CRM_INTEGRATION_LOG;
COMMIT;

DECLARE
    v_reg_id_prop   NUMBER;
    v_reg_id_bld    NUMBER;
    v_reg_id_flr    NUMBER;
    v_reg_id_unit   NUMBER;
    v_reg_id_ust    NUMBER;

    PROCEDURE ins_log(
        p_reg_id  NUMBER,  p_src_id  VARCHAR2,
        p_status  VARCHAR2, p_err_code VARCHAR2,
        p_err_msg VARCHAR2, p_retry   NUMBER,
        p_manual  VARCHAR2, p_attempt NUMBER,
        p_ack_status VARCHAR2 DEFAULT '0000')
    IS
    BEGIN
        INSERT INTO CRM_MPM_CRM_INTEGRATION_LOG (
            REGISTRY_ID, SOURCE_RECORD_ID, ENTITY_NAME,
            OPERATION_TYPE, ATTEMPT_NO,
            REQUEST_PAYLOAD, SENT_DATE,
            FINAL_STATUS, ERROR_CODE, ERROR_MESSAGE,
            ACK_STATUS_CODE, ACK_REQUEST_ID,
            RETRY_COUNT, IS_FINAL_ATTEMPT,
            MANUAL_RETRY, IS_ACTIVE,
            CREATED_DATE, UPDATED_DATE)
        SELECT
            p_reg_id, p_src_id, R.ENTITY_NAME,
            R.OPERATION_TYPE, p_attempt,
            '{"'||R.SOURCE_KEY_COL||'":"'||p_src_id||'","test":"SIT sample data"}',
            SYSTIMESTAMP - (p_retry * 0.02),
            p_status, p_err_code, p_err_msg,
            p_ack_status,
            'REQ-SIT-'||p_src_id||'-'||p_attempt,
            p_retry,
            CASE WHEN p_retry >= 3 THEN 'Y' ELSE 'N' END,
            p_manual, 'Y',
            SYSTIMESTAMP - (p_retry * 0.02), SYSTIMESTAMP
        FROM CRM_MPM_API_REGISTRY R
        WHERE R.REGISTRY_ID = p_reg_id;
    END;

BEGIN
    SELECT REGISTRY_ID INTO v_reg_id_prop FROM CRM_MPM_API_REGISTRY WHERE SERVICE_NAME='MD_PROJECT_CREATE';
    SELECT REGISTRY_ID INTO v_reg_id_bld  FROM CRM_MPM_API_REGISTRY WHERE SERVICE_NAME='MD_BUILDING_CREATE';
    SELECT REGISTRY_ID INTO v_reg_id_flr  FROM CRM_MPM_API_REGISTRY WHERE SERVICE_NAME='MD_FLOOR_CREATE';
    SELECT REGISTRY_ID INTO v_reg_id_unit FROM CRM_MPM_API_REGISTRY WHERE SERVICE_NAME='MD_UNIT_CREATE';
    SELECT REGISTRY_ID INTO v_reg_id_ust  FROM CRM_MPM_API_REGISTRY WHERE SERVICE_NAME='MD_UNIT_STATUS_UPDATE';

    -- SUCCESS records
    ins_log(v_reg_id_prop,'PROP-001','SUCCESS',  NULL,  NULL,                        0,'N',1,'0000');
    ins_log(v_reg_id_prop,'PROP-002','SUCCESS',  NULL,  NULL,                        0,'N',1,'0000');
    ins_log(v_reg_id_bld, 'BLD-001', 'SUCCESS',  NULL,  NULL,                        0,'N',1,'0000');
    ins_log(v_reg_id_bld, 'BLD-002', 'SUCCESS',  NULL,  NULL,                        0,'N',1,'0000');
    ins_log(v_reg_id_flr, 'FLR-001', 'SUCCESS',  NULL,  NULL,                        0,'N',1,'0000');
    ins_log(v_reg_id_unit,'UNIT-001','SUCCESS',  NULL,  NULL,                        0,'N',1,'0000');
    ins_log(v_reg_id_ust, 'UNIT-001','SUCCESS',  NULL,  NULL,                        0,'N',1,'0000');

    -- SENT (waiting callback)
    ins_log(v_reg_id_prop,'PROP-003','SENT',     NULL,  NULL,                        0,'N',1,'0000');
    ins_log(v_reg_id_bld, 'BLD-003', 'SENT',     NULL,  NULL,                        0,'N',1,'0000');
    ins_log(v_reg_id_unit,'UNIT-002','SENT',     NULL,  NULL,                        0,'N',1,'0000');

    -- FAILED (auto retry pending)
    ins_log(v_reg_id_unit,'UNIT-003','FAILED',   'CONN_FAILED',
            'Network timeout connecting to APIC endpoint',1,'N',1,'9999');
    ins_log(v_reg_id_unit,'UNIT-004','FAILED',   'AUTH_FAILED',
            'HTTP 401 token expired',                    1,'N',1,'9999');
    ins_log(v_reg_id_flr, 'FLR-002', 'FAILED',   'FAILURE',
            'PxRM rejected record status=9999',          1,'N',1,'9999');

    -- TIMEOUT (no callback received)
    ins_log(v_reg_id_bld, 'BLD-004', 'TIMEOUT',  'TIMEOUT',
            'No callback received within 60 minutes',    1,'N',1,'0000');
    ins_log(v_reg_id_prop,'PROP-004','TIMEOUT',  'TIMEOUT',
            'No callback received within 60 minutes',    2,'N',2,'0000');

    -- EXHAUSTED (max retries done)
    ins_log(v_reg_id_unit,'UNIT-005','EXHAUSTED','CONN_FAILED',
            'Max retries reached -- network timeout',    3,'N',3,'9999');
    ins_log(v_reg_id_flr, 'FLR-003', 'EXHAUSTED','MANDATORY_FIELD_MISSING',
            'Mandatory field validation failed: floor_name is required',3,'N',3,'9999');

    -- VALIDATION_FAILED
    ins_log(v_reg_id_unit,'UNIT-006','VALIDATION_FAILED','MANDATORY_FIELD_MISSING',
            'Mandatory field validation failed: unit_type is required',0,'N',1,'9999');
    ins_log(v_reg_id_unit,'UNIT-007','VALIDATION_FAILED','INVALID_JSON',
            'Payload is not valid JSON: unexpected token at position 45',0,'N',1,'9999');

    -- RECORD_NOT_FOUND (parent-child issue)
    ins_log(v_reg_id_unit,'UNIT-008','RECORD_NOT_FOUND','LOOKUP_VALIDATION_FAILED',
            'Lookup validation failed for floor_id -> md_floor. Parent floor not found in PxRM',
            1,'N',1,'9999');

    -- CRM_REJECTED
    ins_log(v_reg_id_prop,'PROP-005','CRM_REJECTED','CONFIG_NOT_FOUND',
            'Integration master configuration missing in PxRM for entity md_project',
            0,'N',1,'9999');

    -- DUPLICATE_RECORD
    ins_log(v_reg_id_unit,'UNIT-009','DUPLICATE_RECORD','DUPLICATE_RECORD',
            'Duplicate record found for primary field value UNIT-009',  0,'N',1,'9999');

    -- MANUAL_RETRY (in retry queue)
    ins_log(v_reg_id_unit,'UNIT-010','FAILED',   'CONN_FAILED',
            'Network timeout -- manual retry queued',    0,'Y',2,'9999');

    -- RESOLVED
    ins_log(v_reg_id_flr, 'FLR-004', 'RESOLVED', NULL,
            'Resolved: SUCCESS entry exists. Auto-resolved 24-SEP-26',   1,'Y',1,'9999');

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Done: Integration log sample records inserted');
END;
/

PROMPT --- SECTION 5 COMPLETE ---
PROMPT

-- =============================================================================
-- SECTION 6: CALLBACK AUDIT LOG -- sample callbacks
-- =============================================================================
PROMPT --- SECTION 6: CALLBACK AUDIT LOG ---

DELETE FROM CRM_MPM_CALLBACK_AUDIT_LOG;
COMMIT;

INSERT INTO CRM_MPM_CALLBACK_AUDIT_LOG
    (AUDIT_ID, RECEIVED_AT, SERVICE_NAME, X_UNIQUE_ID, CHANNEL_ID,
     REQUEST_ID, RAW_PAYLOAD, STATUS_CODE_SENT, DESCRIPTION_SENT, CREATED_DATE)
VALUES (CRM_MPM_AUDIT_SEQ.NEXTVAL, SYSTIMESTAMP-0.01,
    'MD_UNIT_CREATE','81424092611430221001','PCRM',
    'abc123-def456-ghi789',
    '{"status":"9999","result_code":"MANDATORY_FIELD_MISSING","result_description":"unit_type is required"}',
    'CB_0000','Callback processed successfully. FINAL_STATUS=VALIDATION_FAILED LOG_ID=1 SERVICE=MD_UNIT_CREATE',
    SYSTIMESTAMP-0.01);

INSERT INTO CRM_MPM_CALLBACK_AUDIT_LOG
    (AUDIT_ID, RECEIVED_AT, SERVICE_NAME, X_UNIQUE_ID, CHANNEL_ID,
     REQUEST_ID, RAW_PAYLOAD, STATUS_CODE_SENT, DESCRIPTION_SENT, CREATED_DATE)
VALUES (CRM_MPM_AUDIT_SEQ.NEXTVAL, SYSTIMESTAMP-0.02,
    'MD_PROJECT_CREATE','81424092611430221002','PCRM',
    'xyz789-abc123-def456',
    '{"status":"0000","result_code":"SUCCESS","crm_entity_id":"GUID-1234-5678"}',
    'CB_0000','Callback processed successfully. FINAL_STATUS=SUCCESS LOG_ID=2 SERVICE=MD_PROJECT_CREATE',
    SYSTIMESTAMP-0.02);

INSERT INTO CRM_MPM_CALLBACK_AUDIT_LOG
    (AUDIT_ID, RECEIVED_AT, SERVICE_NAME, X_UNIQUE_ID, CHANNEL_ID,
     REQUEST_ID, RAW_PAYLOAD, STATUS_CODE_SENT, DESCRIPTION_SENT, CREATED_DATE)
VALUES (CRM_MPM_AUDIT_SEQ.NEXTVAL, SYSTIMESTAMP-0.03,
    'MD_PROJECT_UPDATE','81424092611430221003','PCRM',
    'fe837cbc-71b6-f111-aaad-70a8a522614d',
    '{"status":"0000","result_code":"SUCCESS"}',
    'CB_1002','No matching log entry. request_id=fe837cbc-71b6-f111-aaad-70a8a522614d not found for SERVICE_NAME=MD_PROJECT_UPDATE',
    SYSTIMESTAMP-0.03);

INSERT INTO CRM_MPM_CALLBACK_AUDIT_LOG
    (AUDIT_ID, RECEIVED_AT, SERVICE_NAME, X_UNIQUE_ID, CHANNEL_ID,
     REQUEST_ID, RAW_PAYLOAD, STATUS_CODE_SENT, DESCRIPTION_SENT, CREATED_DATE)
VALUES (CRM_MPM_AUDIT_SEQ.NEXTVAL, SYSTIMESTAMP-0.04,
    'MD_BUILDING_CREATE','81424092611430221004','PCRM',
    'bld-req-001-abc',
    '{"status":"9999","result_code":"LOOKUP_VALIDATION_FAILED","result_description":"Parent property not found in PxRM"}',
    'CB_0000','Callback processed successfully. FINAL_STATUS=RECORD_NOT_FOUND LOG_ID=3 SERVICE=MD_BUILDING_CREATE',
    SYSTIMESTAMP-0.04);

COMMIT;
DBMS_OUTPUT.PUT_LINE('Done: Callback audit log sample records');

PROMPT --- SECTION 6 COMPLETE ---
PROMPT

-- =============================================================================
-- SECTION 7: JOB RUN HISTORY -- sample scheduler run history
-- =============================================================================
PROMPT --- SECTION 7: JOB RUN HISTORY ---

DELETE FROM CRM_MPM_JOB_RUN_HISTORY;
COMMIT;

INSERT INTO CRM_MPM_JOB_RUN_HISTORY
    (RUN_ID, JOB_NAME, START_TIME, END_TIME, STATUS,
     RECORDS_PROCESSED, RECORDS_SUCCESS, RECORDS_FAILED)
VALUES (CRM_MPM_JOB_RUN_SEQ.NEXTVAL,
    'OUTBOUND_JOB', SYSTIMESTAMP-0.04, SYSTIMESTAMP-0.039,
    'COMPLETED', 15, 13, 2);

INSERT INTO CRM_MPM_JOB_RUN_HISTORY
    (RUN_ID, JOB_NAME, START_TIME, END_TIME, STATUS,
     RECORDS_PROCESSED, RECORDS_SUCCESS, RECORDS_FAILED)
VALUES (CRM_MPM_JOB_RUN_SEQ.NEXTVAL,
    'RETRY_JOB', SYSTIMESTAMP-0.03, SYSTIMESTAMP-0.029,
    'COMPLETED', 3, 2, 1);

INSERT INTO CRM_MPM_JOB_RUN_HISTORY
    (RUN_ID, JOB_NAME, START_TIME, END_TIME, STATUS,
     RECORDS_PROCESSED, RECORDS_SUCCESS, RECORDS_FAILED)
VALUES (CRM_MPM_JOB_RUN_SEQ.NEXTVAL,
    'TIMEOUT_JOB', SYSTIMESTAMP-0.02, SYSTIMESTAMP-0.019,
    'COMPLETED', 2, 0, 2);

INSERT INTO CRM_MPM_JOB_RUN_HISTORY
    (RUN_ID, JOB_NAME, START_TIME, END_TIME, STATUS,
     RECORDS_PROCESSED, RECORDS_SUCCESS, RECORDS_FAILED)
VALUES (CRM_MPM_JOB_RUN_SEQ.NEXTVAL,
    'OUTBOUND_JOB', SYSTIMESTAMP-0.01, SYSTIMESTAMP-0.009,
    'COMPLETED', 8, 7, 1);

COMMIT;
DBMS_OUTPUT.PUT_LINE('Done: Job run history sample records');

PROMPT --- SECTION 7 COMPLETE ---
PROMPT

-- =============================================================================
-- SECTION 8: VERIFY ALL DATA
-- =============================================================================
PROMPT --- SECTION 8: VERIFY ---

PROMPT Credentials:
SELECT CRED_CODE, CLIENT_ID, IS_ACTIVE,
       SUBSTR(TOKEN_URL,1,60) AS TOKEN_URL
FROM   CRM_MPM_API_CREDENTIALS;

PROMPT Registry (9 rows expected):
SELECT SERVICE_NAME, ENTITY_NAME, IS_ACTIVE, EXECUTION_ORDER
FROM   CRM_MPM_API_REGISTRY ORDER BY EXECUTION_ORDER;

PROMPT Field Mappings per service:
SELECT JSON_MAPPING_NAME, COUNT(*) AS FIELDS
FROM   CRM_MPM_API_FIELD_MAPPING
GROUP  BY JSON_MAPPING_NAME ORDER BY JSON_MAPPING_NAME;

PROMPT Watermark:
SELECT R.SERVICE_NAME,
       TO_CHAR(W.LAST_PROCESSED_TS,'DD-MON-YY HH24:MI') AS LAST_PROCESSED
FROM   CRM_MPM_API_WATERMARK W
JOIN   CRM_MPM_API_REGISTRY R ON R.REGISTRY_ID=W.REGISTRY_ID
ORDER  BY R.EXECUTION_ORDER;

PROMPT Integration Log by status:
SELECT FINAL_STATUS, COUNT(*) AS CNT
FROM   CRM_MPM_CRM_INTEGRATION_LOG
GROUP  BY FINAL_STATUS ORDER BY FINAL_STATUS;

PROMPT Callback Audit:
SELECT STATUS_CODE_SENT, COUNT(*) AS CNT
FROM   CRM_MPM_CALLBACK_AUDIT_LOG
GROUP  BY STATUS_CODE_SENT;

PROMPT Job History:
SELECT JOB_NAME, STATUS, RECORDS_PROCESSED, RECORDS_SUCCESS
FROM   CRM_MPM_JOB_RUN_HISTORY ORDER BY RUN_ID;

PROMPT
PROMPT =============================================================
PROMPT   SIT FULL DATA INSERT COMPLETE
PROMPT   All tabs in Admin Tool should now show data
PROMPT   Dashboard, All Records, Action Needed, Retry Queue,
PROMPT   Error Triage, Callback Audit -- all populated
PROMPT =============================================================

-- =============================================================================
-- SECTION 9: ERROR CODE MASTER (missing from earlier)
-- =============================================================================
PROMPT --- SECTION 9: ERROR CODES ---

DELETE FROM CRM_MPM_ERROR_CODE_MASTER;
COMMIT;

-- CRM side
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'INVALID_JSON' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('INVALID_JSON','Payload is not valid JSON','N','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'CONFIG_NOT_FOUND' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('CONFIG_NOT_FOUND','Integration master missing in PxRM','N','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'MANDATORY_FIELD_MISSING' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('MANDATORY_FIELD_MISSING','Mandatory field missing in payload','N','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'PRIMARY_FIELD_MISSING' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('PRIMARY_FIELD_MISSING','Primary key field missing in payload','N','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'LOOKUP_VALIDATION_FAILED' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('LOOKUP_VALIDATION_FAILED','Parent record not found in PxRM','Y','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'DUPLICATE_RECORD' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('DUPLICATE_RECORD','Record already exists in PxRM','N','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'VALIDATION_FAILED' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('VALIDATION_FAILED','Unknown validation error fallback','N','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'FAILURE' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('FAILURE','Generic PostOperation failure','Y','Y');
-- MPM side
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'CONN_FAILED' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('CONN_FAILED','Network/APIC connection timeout','Y','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'AUTH_FAILED' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('AUTH_FAILED','HTTP 401/403 token or auth failure','Y','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'APIC_ERROR' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('APIC_ERROR','APIC HTTP server error','Y','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'VALIDATION_ERROR' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('VALIDATION_ERROR','HTTP 4xx bad request from APIC','Y','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'UNKNOWN_ERROR' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('UNKNOWN_ERROR','Unclassified error','Y','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'AUTH_OR_HEADER_ERROR' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('AUTH_OR_HEADER_ERROR','Missing header or auth rejected at APIC','Y','Y');
-- Status codes
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'CB_0000' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('CB_0000','Callback processed successfully','N','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'CB_1002' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('CB_1002','No matching log entry for callback','Y','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'TIMEOUT' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('TIMEOUT','No callback within timeout threshold','Y','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'EXHAUSTED' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('EXHAUSTED','All retries exhausted -- manual intervention','N','Y');
MERGE INTO CRM_MPM_ERROR_CODE_MASTER T USING (SELECT 'SUCCESS' C FROM DUAL) S ON (T.ERROR_CODE=S.C)
WHEN NOT MATCHED THEN INSERT (ERROR_CODE,ERROR_DESCRIPTION,IS_RETRYABLE,IS_ACTIVE) VALUES ('SUCCESS','Successfully processed by CRM','N','Y');

COMMIT;
DBMS_OUTPUT.PUT_LINE('Done: 19 error codes inserted');

-- =============================================================================
-- SECTION 10: FIX MAPPING_ID -- populate using sequence
-- =============================================================================
PROMPT --- SECTION 10: FIX MAPPING_ID ---

-- Populate MAPPING_ID using sequence for all rows that have NULL
BEGIN
    FOR r IN (SELECT ROWID AS RID FROM CRM_MPM_API_FIELD_MAPPING WHERE MAPPING_ID IS NULL) LOOP
        UPDATE CRM_MPM_API_FIELD_MAPPING
        SET MAPPING_ID = CRM_MPM_MAPPING_SEQ.NEXTVAL
        WHERE ROWID = r.RID;
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Done: MAPPING_ID populated for '||SQL%ROWCOUNT||' rows');
END;
/

PROMPT --- ALL SECTIONS COMPLETE ---

-- Final count check
SELECT 'CRM_MPM_API_CREDENTIALS'     AS TBL, COUNT(*) CNT FROM CRM_MPM_API_CREDENTIALS    UNION ALL
SELECT 'CRM_MPM_API_REGISTRY'        AS TBL, COUNT(*) CNT FROM CRM_MPM_API_REGISTRY         UNION ALL
SELECT 'CRM_MPM_API_FIELD_MAPPING'   AS TBL, COUNT(*) CNT FROM CRM_MPM_API_FIELD_MAPPING    UNION ALL
SELECT 'CRM_MPM_API_WATERMARK'       AS TBL, COUNT(*) CNT FROM CRM_MPM_API_WATERMARK        UNION ALL
SELECT 'CRM_MPM_ERROR_CODE_MASTER'   AS TBL, COUNT(*) CNT FROM CRM_MPM_ERROR_CODE_MASTER    UNION ALL
SELECT 'CRM_MPM_CRM_INTEGRATION_LOG' AS TBL, COUNT(*) CNT FROM CRM_MPM_CRM_INTEGRATION_LOG  UNION ALL
SELECT 'CRM_MPM_CALLBACK_AUDIT_LOG'  AS TBL, COUNT(*) CNT FROM CRM_MPM_CALLBACK_AUDIT_LOG   UNION ALL
SELECT 'CRM_MPM_JOB_RUN_HISTORY'     AS TBL, COUNT(*) CNT FROM CRM_MPM_JOB_RUN_HISTORY      UNION ALL
SELECT 'CRM_MPM_ENCRYPT_CONFIG'      AS TBL, COUNT(*) CNT FROM CRM_MPM_ENCRYPT_CONFIG       UNION ALL
SELECT 'CRM_MPM_UNIQUE_ID_CONFIG'    AS TBL, COUNT(*) CNT FROM CRM_MPM_UNIQUE_ID_CONFIG
ORDER BY TBL;

PROMPT
PROMPT =============================================================
PROMPT   SIT FULL DATA INSERT -- TRULY COMPLETE
PROMPT   10 tables all populated with data
PROMPT =============================================================
